### ISSUE TITLE
Hardcode required OpenID scopes, leave only API scope as configurable

### ISSUE THREAD

**Issue by vikoivun** [City-of-Helsinki/mvj-ui#385]
Currently mvj-ui requires the server admin to add all needed scopes when configuring OPENID_CONNECT_SCOPE:
https://github.com/City-of-Helsinki/mvj-ui/blob/131dca81240ee77c56ec04764ed7531c8cf055cc/src/auth/util/user-manager.js#L12

Both "openid" and "profile" are mandatory for mvi-ui (former is mandatory per OpenID Connect, latter causes Tunnistamo to return name + email). So they can be both hardcoded.

Only API scope needs to be configurable. I suggest a name like `HEL_API_TOKEN_SCOPE`, contents of which would be appended to the scopes here.

Additionally the API scope will always be equal to the key in the list of API tokens returned by tunnistamo. So this:
https://github.com/City-of-Helsinki/mvj-ui/blob/131dca81240ee77c56ec04764ed7531c8cf055cc/src/auth/selectors.js#L7-L9
can use the exact same configuration variable. No need to replicate the same value in two different settings.

This makes configuration more robust against typos and forgetfulness.

**Comment by NC-jsAhonen** [comment]
Moved to team's Jira ticket board.
